// <auto-generated/>
#nullable enable

using Exanite.Engine.Resources;
using Exanite.ResourceManagement;

namespace Exanite.GravitationalTetris;

[GeneratedResourceClass]
public partial class GravitationalTetrisResources
{
    // Path: Exanite.GravitationalTetris

    public static readonly ResourceDefinition<global::Exanite.Prowl.Paper.FontFile> ExaniteGravitationalTetris_FieryTurkFont = new("/Exanite.GravitationalTetris/FieryTurk.ttf");

    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_PlayerSprite = new("/Exanite.GravitationalTetris/Player.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileBlueSprite = new("/Exanite.GravitationalTetris/TileBlue.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileCyanSprite = new("/Exanite.GravitationalTetris/TileCyan.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileGreenSprite = new("/Exanite.GravitationalTetris/TileGreen.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileNoneSprite = new("/Exanite.GravitationalTetris/TileNone.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileOrangeSprite = new("/Exanite.GravitationalTetris/TileOrange.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TilePlaceholderSprite = new("/Exanite.GravitationalTetris/TilePlaceholder.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TilePurpleSprite = new("/Exanite.GravitationalTetris/TilePurple.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileRedSprite = new("/Exanite.GravitationalTetris/TileRed.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileYellowSprite = new("/Exanite.GravitationalTetris/TileYellow.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_WhiteSprite = new("/Exanite.GravitationalTetris/White.png");

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_PlayerTexture = new("/Exanite.GravitationalTetris/Player.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileBlueTexture = new("/Exanite.GravitationalTetris/TileBlue.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileCyanTexture = new("/Exanite.GravitationalTetris/TileCyan.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileGreenTexture = new("/Exanite.GravitationalTetris/TileGreen.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileNoneTexture = new("/Exanite.GravitationalTetris/TileNone.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileOrangeTexture = new("/Exanite.GravitationalTetris/TileOrange.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TilePlaceholderTexture = new("/Exanite.GravitationalTetris/TilePlaceholder.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TilePurpleTexture = new("/Exanite.GravitationalTetris/TilePurple.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileRedTexture = new("/Exanite.GravitationalTetris/TileRed.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileYellowTexture = new("/Exanite.GravitationalTetris/TileYellow.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_WhiteTexture = new("/Exanite.GravitationalTetris/White.png");

    // Path: Exanite.GravitationalTetris/Audio

    public static readonly ResourceDefinition<global::Exanite.Engine.Audio.AudioData> ExaniteGravitationalTetris_Audio_ClearTileAudio = new("/Exanite.GravitationalTetris/Audio/ClearTile.wav");
    public static readonly ResourceDefinition<global::Exanite.Engine.Audio.AudioData> ExaniteGravitationalTetris_Audio_RestartAudio = new("/Exanite.GravitationalTetris/Audio/Restart.wav");
    public static readonly ResourceDefinition<global::Exanite.Engine.Audio.AudioData> ExaniteGravitationalTetris_Audio_RotateShapeAudio = new("/Exanite.GravitationalTetris/Audio/RotateShape.wav");
    public static readonly ResourceDefinition<global::Exanite.Engine.Audio.AudioData> ExaniteGravitationalTetris_Audio_SwitchGravityAudio = new("/Exanite.GravitationalTetris/Audio/SwitchGravity.wav");

    // Path: Exanite.GravitationalTetris.Winter

    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_PlayerSprite = new("/Exanite.GravitationalTetris.Winter/Player.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileBlueSprite = new("/Exanite.GravitationalTetris.Winter/TileBlue.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileCyanSprite = new("/Exanite.GravitationalTetris.Winter/TileCyan.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileGreenSprite = new("/Exanite.GravitationalTetris.Winter/TileGreen.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileOrangeSprite = new("/Exanite.GravitationalTetris.Winter/TileOrange.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TilePurpleSprite = new("/Exanite.GravitationalTetris.Winter/TilePurple.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileRedSprite = new("/Exanite.GravitationalTetris.Winter/TileRed.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileYellowSprite = new("/Exanite.GravitationalTetris.Winter/TileYellow.png");

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_PlayerTexture = new("/Exanite.GravitationalTetris.Winter/Player.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileBlueTexture = new("/Exanite.GravitationalTetris.Winter/TileBlue.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileCyanTexture = new("/Exanite.GravitationalTetris.Winter/TileCyan.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileGreenTexture = new("/Exanite.GravitationalTetris.Winter/TileGreen.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileOrangeTexture = new("/Exanite.GravitationalTetris.Winter/TileOrange.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TilePurpleTexture = new("/Exanite.GravitationalTetris.Winter/TilePurple.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileRedTexture = new("/Exanite.GravitationalTetris.Winter/TileRed.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileYellowTexture = new("/Exanite.GravitationalTetris.Winter/TileYellow.png");
}
