// <auto-generated/>
#nullable enable

using Exanite.Engine.ResourceManagement;
using Exanite.ResourceManagement;

namespace Exanite.GravitationalTetris;

[GeneratedResourceClass]
internal partial class Resources
{
    // Path: Exanite.Engine/Rendering

    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteEngine_Rendering_Icon_Sprite = new("/Exanite.Engine/Icon.png");

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteEngine_Rendering_Icon_Texture = new("/Exanite.Engine/Icon.png");

    // Path: Exanite.Engine/Fonts

    public static readonly ResourceDefinition<global::Exanite.Prowl.Paper.FontFile> ExaniteEngine_Fonts_FieryTurk_Font = new("/Exanite.Engine/Fonts/FieryTurk.ttf");
    public static readonly ResourceDefinition<global::Exanite.Prowl.Paper.FontFile> ExaniteEngine_Fonts_NotoSansRegular_Font = new("/Exanite.Engine/Fonts/NotoSans-Regular.ttf");

    // Path: Exanite.Engine/PostProcessing

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_PostProcessing_BloomDown_FragmentModule = new("/Exanite.Engine/PostProcessing/BloomDown.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_PostProcessing_BloomUp_FragmentModule = new("/Exanite.Engine/PostProcessing/BloomUp.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_PostProcessing_ToneMap_FragmentModule = new("/Exanite.Engine/PostProcessing/ToneMap.fragment.slang");

    // Path: Exanite.Engine/Rendering

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Rendering_Blit_FragmentModule = new("/Exanite.Engine/Rendering/Blit.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Rendering_ScreenQuad_VertexModule = new("/Exanite.Engine/Rendering/ScreenQuad.vertex.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Rendering_ScreenTri_VertexModule = new("/Exanite.Engine/Rendering/ScreenTri.vertex.slang");

    // Path: Exanite.Engine/Sprites

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Sprites_Sprite_FragmentModule = new("/Exanite.Engine/Sprites/Sprite.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Sprites_Sprite_VertexModule = new("/Exanite.Engine/Sprites/Sprite.vertex.slang");

    // Path: Exanite.Engine/UserInterfaces

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_UserInterfaces_Ui_FragmentModule = new("/Exanite.Engine/UserInterfaces/Ui.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_UserInterfaces_Ui_VertexModule = new("/Exanite.Engine/UserInterfaces/Ui.vertex.slang");

    // Path: Exanite.GravitationalTetris

    public static readonly ResourceDefinition<global::Exanite.Prowl.Paper.FontFile> ExaniteGravitationalTetris_FieryTurk_Font = new("/Exanite.GravitationalTetris/FieryTurk.ttf");

    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_Player_Sprite = new("/Exanite.GravitationalTetris/Player.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileBlue_Sprite = new("/Exanite.GravitationalTetris/TileBlue.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileCyan_Sprite = new("/Exanite.GravitationalTetris/TileCyan.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileGreen_Sprite = new("/Exanite.GravitationalTetris/TileGreen.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileNone_Sprite = new("/Exanite.GravitationalTetris/TileNone.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileOrange_Sprite = new("/Exanite.GravitationalTetris/TileOrange.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TilePlaceholder_Sprite = new("/Exanite.GravitationalTetris/TilePlaceholder.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TilePurple_Sprite = new("/Exanite.GravitationalTetris/TilePurple.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileRed_Sprite = new("/Exanite.GravitationalTetris/TileRed.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_TileYellow_Sprite = new("/Exanite.GravitationalTetris/TileYellow.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetris_White_Sprite = new("/Exanite.GravitationalTetris/White.png");

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_Player_Texture = new("/Exanite.GravitationalTetris/Player.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileBlue_Texture = new("/Exanite.GravitationalTetris/TileBlue.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileCyan_Texture = new("/Exanite.GravitationalTetris/TileCyan.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileGreen_Texture = new("/Exanite.GravitationalTetris/TileGreen.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileNone_Texture = new("/Exanite.GravitationalTetris/TileNone.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileOrange_Texture = new("/Exanite.GravitationalTetris/TileOrange.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TilePlaceholder_Texture = new("/Exanite.GravitationalTetris/TilePlaceholder.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TilePurple_Texture = new("/Exanite.GravitationalTetris/TilePurple.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileRed_Texture = new("/Exanite.GravitationalTetris/TileRed.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_TileYellow_Texture = new("/Exanite.GravitationalTetris/TileYellow.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetris_White_Texture = new("/Exanite.GravitationalTetris/White.png");

    // Path: Exanite.GravitationalTetris/Audio

    public static readonly ResourceDefinition<global::Exanite.Engine.Audio.AudioData> ExaniteGravitationalTetris_Audio_ClearTile_Audio = new("/Exanite.GravitationalTetris/Audio/ClearTile.wav");
    public static readonly ResourceDefinition<global::Exanite.Engine.Audio.AudioData> ExaniteGravitationalTetris_Audio_Restart_Audio = new("/Exanite.GravitationalTetris/Audio/Restart.wav");
    public static readonly ResourceDefinition<global::Exanite.Engine.Audio.AudioData> ExaniteGravitationalTetris_Audio_RotateShape_Audio = new("/Exanite.GravitationalTetris/Audio/RotateShape.wav");
    public static readonly ResourceDefinition<global::Exanite.Engine.Audio.AudioData> ExaniteGravitationalTetris_Audio_SwitchGravity_Audio = new("/Exanite.GravitationalTetris/Audio/SwitchGravity.wav");

    // Path: Exanite.GravitationalTetris.Winter

    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_Player_Sprite = new("/Exanite.GravitationalTetris.Winter/Player.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileBlue_Sprite = new("/Exanite.GravitationalTetris.Winter/TileBlue.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileCyan_Sprite = new("/Exanite.GravitationalTetris.Winter/TileCyan.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileGreen_Sprite = new("/Exanite.GravitationalTetris.Winter/TileGreen.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileOrange_Sprite = new("/Exanite.GravitationalTetris.Winter/TileOrange.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TilePurple_Sprite = new("/Exanite.GravitationalTetris.Winter/TilePurple.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileRed_Sprite = new("/Exanite.GravitationalTetris.Winter/TileRed.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteGravitationalTetrisWinter_TileYellow_Sprite = new("/Exanite.GravitationalTetris.Winter/TileYellow.png");

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_Player_Texture = new("/Exanite.GravitationalTetris.Winter/Player.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileBlue_Texture = new("/Exanite.GravitationalTetris.Winter/TileBlue.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileCyan_Texture = new("/Exanite.GravitationalTetris.Winter/TileCyan.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileGreen_Texture = new("/Exanite.GravitationalTetris.Winter/TileGreen.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileOrange_Texture = new("/Exanite.GravitationalTetris.Winter/TileOrange.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TilePurple_Texture = new("/Exanite.GravitationalTetris.Winter/TilePurple.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileRed_Texture = new("/Exanite.GravitationalTetris.Winter/TileRed.png");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteGravitationalTetrisWinter_TileYellow_Texture = new("/Exanite.GravitationalTetris.Winter/TileYellow.png");
}
